export type MuscleCategory = 'chest' | 'back' | 'shoulders' | 'arms' | 'legs' | 'core';

export type EquipmentCategory =
  | 'dumbbell'
  | 'barbell'
  | 'cable'
  | 'machine'
  | 'smith_machine'
  | 'bodyweight';

export interface MuscleExerciseGuide {
  id: string;
  name: string;
  nameId: string;
  muscleCategory: MuscleCategory;
  subMuscle: string;
  subMuscleId: string;
  equipment: EquipmentCategory;
  equipmentNameId: string;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  equipmentLookFor: string; // Machine description in commercial gyms
  setupTips: string;
  mindMuscleCue: string;
  defaultRepRange: string;
}

export interface SubMuscleInfo {
  id: string;
  name: string;
  nameId: string;
  functionDesc: string;
  visualRole: string;
}

export const MUSCLE_BREAKDOWN: Record<
  MuscleCategory,
  {
    name: string;
    nameId: string;
    description: string;
    subMuscles: SubMuscleInfo[];
  }
> = {
  chest: {
    name: 'Chest',
    nameId: 'Dada (Pectoralis)',
    description: 'Otot dada terbagi menjadi 3 serat utama: serat atas (clavicular), tengah (sternal), dan bawah (abdominal).',
    subMuscles: [
      {
        id: 'upper_chest',
        name: 'Upper Chest',
        nameId: 'Dada Atas (Clavicular Head)',
        functionDesc: 'Fleksi bahu dan adduksi ke arah atas.',
        visualRole: 'Memberikan kesan dada penuh dan tegak di bawah tulang selangka.',
      },
      {
        id: 'mid_chest',
        name: 'Mid Chest',
        nameId: 'Dada Tengah (Sternal Head)',
        functionDesc: 'Adduksi horizontal merapatkan kedua lengan ke tengah.',
        visualRole: 'Menciptakan ketebalan dan belahan dada yang jelas.',
      },
      {
        id: 'lower_chest',
        name: 'Lower Chest',
        nameId: 'Dada Bawah (Abdominal Head)',
        functionDesc: 'Menarik lengan ke bawah dan ke arah dalam tubuh.',
        visualRole: 'Membentuk garis bawah dada yang tajam dan tegas.',
      },
    ],
  },
  back: {
    name: 'Back',
    nameId: 'Punggung (Latissimus & Upper Back)',
    description: 'Punggung membutuhkan variasi tarikan vertikal (untuk lebar V-taper) dan horizontal (untuk ketebalan).',
    subMuscles: [
      {
        id: 'lats',
        name: 'Lats (Latissimus Dorsi)',
        nameId: 'Sayap / Lats (Lebar Punggung)',
        functionDesc: 'Menarik lengan ke arah pinggul dan adduksi bahu.',
        visualRole: 'Kunci utama siluet V-Taper atletis yang membuat pinggang terlihat lebih ramping.',
      },
      {
        id: 'rhomboids_traps',
        name: 'Upper & Mid Back (Traps & Rhomboids)',
        nameId: 'Punggung Tengah & Atas (Ketebalan)',
        functionDesc: 'Retraksi dan elevasi tulang belikat (scapula).',
        visualRole: 'Memberikan kepadatan otot saat dilihat dari samping dan belakang.',
      },
      {
        id: 'lower_back',
        name: 'Lower Back (Erector Spinae)',
        nameId: 'Pinggang Bawah (Erector Spinae)',
        functionDesc: 'Ekstensi tulang belakang dan stabilisasi inti.',
        visualRole: 'Mencegah cedera postur dan menopang kekuatan angkatan squat/deadlift.',
      },
    ],
  },
  shoulders: {
    name: 'Shoulders',
    nameId: 'Bahu (Deltoids)',
    description: 'Bahu terdiri dari 3 kepala (anterior, lateral, posterior). Menargetkan ketiganya menghasilkan bentuk bahu 3D membulat (*boulder shoulders*).',
    subMuscles: [
      {
        id: 'side_delt',
        name: 'Lateral / Side Delt',
        nameId: 'Bahu Samping (Lateral Head)',
        functionDesc: 'Abduksi lengan ke samping menjauhi tubuh.',
        visualRole: 'Paling penting untuk melebarkan bingkai bahu dan siluet atletis.',
      },
      {
        id: 'front_delt',
        name: 'Anterior / Front Delt',
        nameId: 'Bahu Depan (Anterior Head)',
        functionDesc: 'Fleksi bahu mengangkat beban ke depan atas.',
        visualRole: 'Memberikan kepenuhan bagian depan bahu (sering terlatih saat bench press).',
      },
      {
        id: 'rear_delt',
        name: 'Posterior / Rear Delt',
        nameId: 'Bahu Belakang (Posterior Head)',
        functionDesc: 'Abduksi horizontal bahu ke arah belakang.',
        visualRole: 'Menyeimbangkan postur tegap bahu dan memberikan efek 3D bulat sempurna.',
      },
    ],
  },
  arms: {
    name: 'Arms',
    nameId: 'Lengan (Biceps & Triceps)',
    description: 'Triceps menyumbang ~60% dari volume lengan atas, sedangkan Biceps & Brachialis mengisi 40% lainnya.',
    subMuscles: [
      {
        id: 'triceps',
        name: 'Triceps (Long, Lateral, Medial)',
        nameId: 'Triceps (Lengan Belakang)',
        functionDesc: 'Ekstensi siku mendorong beban lurus.',
        visualRole: 'Komponen terbesar yang membuat lengan terlihat berotot dan kokoh.',
      },
      {
        id: 'biceps',
        name: 'Biceps (Long & Short Head)',
        nameId: 'Biceps (Lengan Depan)',
        functionDesc: 'Fleksi siku dan supinasi telapak tangan.',
        visualRole: 'Menciptakan "peak" tonjolan lengan saat menekuk tangan.',
      },
      {
        id: 'brachialis',
        name: 'Brachialis & Forearm',
        nameId: 'Brachialis & Lengan Bawah',
        functionDesc: 'Fleksi siku dengan posisi telapak tangan netral.',
        visualRole: 'Mendorong bicep ke atas dari bawah, membuat lingkar lengan lebih tebal.',
      },
    ],
  },
  legs: {
    name: 'Legs',
    nameId: 'Kaki (Quadriceps, Hamstrings, Glutes, Calves)',
    description: 'Kelompok otot terbesar tubuh penopang metabolisme dan pembakaran kalori harian terbesar.',
    subMuscles: [
      {
        id: 'quads',
        name: 'Quadriceps',
        nameId: 'Paha Depan (Quads)',
        functionDesc: 'Ekstensi lutut meluruskan kaki.',
        visualRole: 'Membentuk lekukan paha depan (*quad sweep*) yang kokoh dan atletis.',
      },
      {
        id: 'hamstrings',
        name: 'Hamstrings',
        nameId: 'Paha Belakang (Hamstrings)',
        functionDesc: 'Fleksi lutut dan ekstensi panggul.',
        visualRole: 'Memberikan kepenuhan bagian belakang paha dan kekuatan sprint/lompat.',
      },
      {
        id: 'glutes',
        name: 'Glutes',
        nameId: 'Bokong (Gluteus Maximus/Medius)',
        functionDesc: 'Ekstensi panggul dan rotasi eksternal.',
        visualRole: 'Penghasil tenaga dorongan panggul utama dan estetika tubuh belakang.',
      },
      {
        id: 'calves',
        name: 'Calves',
        nameId: 'Betis (Gastrocnemius & Soleus)',
        functionDesc: 'Plantar fleksi pergelangan kaki berjinjit.',
        visualRole: 'Memberikan proporsi seimbang antara paha dan kaki bawah.',
      },
    ],
  },
  core: {
    name: 'Core',
    nameId: 'Perut & Otot Inti (Abs & Obliques)',
    description: 'Menstabilkan tulang belakang dan mentransfer tenaga dari tubuh bawah ke tubuh atas.',
    subMuscles: [
      {
        id: 'abs',
        name: 'Rectus Abdominis',
        nameId: 'Perut Tengah / Six-Pack',
        functionDesc: 'Fleksi tulang belakang mendekatkan dada ke pinggul.',
        visualRole: 'Kotak-kotak six-pack yang tampak jelas saat kadar lemak tubuh lean.',
      },
      {
        id: 'obliques',
        name: 'Obliques',
        nameId: 'Otot Pinggang Samping (Obliques)',
        functionDesc: 'Rotasi tubuh dan fleksi lateral ke samping.',
        visualRole: 'Garis V-cut samping pinggang yang atletis.',
      },
    ],
  },
};

export const EXERCISE_EQUIPMENT_GUIDE: MuscleExerciseGuide[] = [
  // ================= DADA (CHEST) =================
  {
    id: 'guide-incline-db-press',
    name: 'Incline Dumbbell Press',
    nameId: 'Incline Dumbbell Press',
    muscleCategory: 'chest',
    subMuscle: 'upper_chest',
    subMuscleId: 'Dada Atas',
    equipment: 'dumbbell',
    equipmentNameId: 'Dumbbell & Bangku Incline',
    difficulty: 'intermediate',
    equipmentLookFor: 'Bangku gym adjustable diatur kemiringan 30°–45° + sepasang Dumbbell.',
    setupTips: 'Atur sandaran bangku 30 derajat (jangan terlalu tegak agar bahu depan tidak mendominasi). Busungkan dada dan tarik bahu ke belakang menempel sandaran.',
    mindMuscleCue: 'Dorong dumbbell ke atas sambil fokus menekan siku ke arah dalam dada atas, bukan hanya meluruskan tangan.',
    defaultRepRange: '6-8 reps',
  },
  {
    id: 'guide-incline-chest-machine',
    name: 'Incline Chest Press Machine',
    nameId: 'Mesin Incline Chest Press',
    muscleCategory: 'chest',
    subMuscle: 'upper_chest',
    subMuscleId: 'Dada Atas',
    equipment: 'machine',
    equipmentNameId: 'Mesin Chest Press Incline (Plate/Pin)',
    difficulty: 'beginner',
    equipmentLookFor: 'Mesin duduk dengan tuas pegangan yang bergerak mendorong miring ke atas.',
    setupTips: 'Atur tinggi jok kursi agar pegangan sejajar dengan garis dada atas Anda. Kaki menapak kuat di lantai.',
    mindMuscleCue: 'Stabil dan aman tanpa takut dumbbell oleng. Dorong penuh dan tahan 1 detik di posisi puncak kontraksi.',
    defaultRepRange: '8-10 reps',
  },
  {
    id: 'guide-flat-bench-press',
    name: 'Barbell Flat Bench Press',
    nameId: 'Barbell Flat Bench Press',
    muscleCategory: 'chest',
    subMuscle: 'mid_chest',
    subMuscleId: 'Dada Tengah',
    equipment: 'barbell',
    equipmentNameId: 'Barbel Olimpiade & Flat Bench',
    difficulty: 'intermediate',
    equipmentLookFor: 'Rak bangku datar dengan barbel panjang standar 20 kg dan kuncian beban (*collar*).',
    setupTips: 'Mata sejajar di bawah barbel. Buka tangan selebar 1.5x bahu. Tarik belikat ke bawah (*retracted scapula*) dan jaga lengkungan punggung alami.',
    mindMuscleCue: 'Turunkan barbel terkontrol menyentuh dada tengah, lalu dorong eksplosif menembus lantai dengan kaki (*leg drive*).',
    defaultRepRange: '6-8 reps',
  },
  {
    id: 'guide-pec-deck-fly',
    name: 'Pec Deck Machine (Machine Fly)',
    nameId: 'Mesin Pec Deck / Butterfly',
    muscleCategory: 'chest',
    subMuscle: 'mid_chest',
    subMuscleId: 'Dada Tengah',
    equipment: 'machine',
    equipmentNameId: 'Mesin Pec Deck Fly',
    difficulty: 'beginner',
    equipmentLookFor: 'Mesin duduk dengan dua lengan tuas berputar yang digerakkan saling merapat ke tengah.',
    setupTips: 'Atur ketinggian kursi agar siku dan tangan Anda berada tepat sejajar di tengah dada.',
    mindMuscleCue: 'Bayangkan Anda sedang memeluk pohon besar. Pertahankan tekukan ringan di siku dan rasakan peregangan maksimal di dada saat membuka.',
    defaultRepRange: '10-12 reps',
  },
  {
    id: 'guide-cable-crossover-high-low',
    name: 'High-to-Low Cable Fly',
    nameId: 'Kabel Fly Atas ke Bawah',
    muscleCategory: 'chest',
    subMuscle: 'lower_chest',
    subMuscleId: 'Dada Bawah',
    equipment: 'cable',
    equipmentNameId: 'Dual Cable Station / Crossover',
    difficulty: 'intermediate',
    equipmentLookFor: 'Tiang kabel ganda, katrol dipasang di posisi paling atas (di atas kepala) dengan pegangan D-Handle tunggal.',
    setupTips: 'Langkah satu kaki ke depan untuk kestabilan tubuh. Bungkukkan badan sedikit ke depan.',
    mindMuscleCue: 'Tarik kabel ke arah bawah dan silangkan sedikit di depan pinggang. Peras otot dada bawah selama 1 detik.',
    defaultRepRange: '10-12 reps',
  },
  {
    id: 'guide-chest-dips',
    name: 'Chest Dips',
    nameId: 'Dips Dada (Parallel Bars)',
    muscleCategory: 'chest',
    subMuscle: 'lower_chest',
    subMuscleId: 'Dada Bawah',
    equipment: 'bodyweight',
    equipmentNameId: 'Palang Dips / Mesin Assisted Dip',
    difficulty: 'advanced',
    equipmentLookFor: 'Dua palang paralel vertikal, atau mesin *assisted dip* dengan bantalan lutut hidrolik.',
    setupTips: 'Condongkan badan ke depan ~30 derajat dan tekuk lutut. Jangan tegak lurus (karena posisi tegak lebih banyak mengenai tricep).',
    mindMuscleCue: 'Turunkan tubuh sampai siku membentuk sudut 90 derajat, rasakan peregangan dada bawah, lalu tekan naik kuat.',
    defaultRepRange: '8-10 reps',
  },

  // ================= PUNGGUNG (BACK) =================
  {
    id: 'guide-lat-pulldown',
    name: 'Lat Pulldown',
    nameId: 'Mesin Lat Pulldown',
    muscleCategory: 'back',
    subMuscle: 'lats',
    subMuscleId: 'Sayap / Lats',
    equipment: 'cable',
    equipmentNameId: 'Mesin Lat Pulldown Kabel',
    difficulty: 'beginner',
    equipmentLookFor: 'Mesin kabel tinggi vertikal dengan stang lebar (*lat bar*) dan bantalan pengunci paha.',
    setupTips: 'Kunci paha rapat di bawah bantalan agar tubuh tidak terangkat. Pegang stang sedikit lebih lebar dari bahu.',
    mindMuscleCue: 'Tarik dengan siku Anda mengarah ke saku celana belakang, jangan menarik hanya dengan tenaga lengan bawah.',
    defaultRepRange: '8-10 reps',
  },
  {
    id: 'guide-seated-cable-row',
    name: 'Seated Cable Row',
    nameId: 'Seated Cable Row (Tarik Duduk)',
    muscleCategory: 'back',
    subMuscle: 'rhomboids_traps',
    subMuscleId: 'Punggung Tengah / Ketebalan',
    equipment: 'cable',
    equipmentNameId: 'Low Cable Row Station & V-Grip Handle',
    difficulty: 'beginner',
    equipmentLookFor: 'Mesin kabel rendah mendatar dengan pijakan kaki dan handle V-Bar segitiga.',
    setupTips: 'Duduk tegap, lutut sedikit ditekuk jangan terkunci lurus. Dada dibusungkan dan bahu dijatuhkan ke bawah.',
    mindMuscleCue: 'Tarik handle ke arah pusar perut sambil merapatkan kedua tulang belikat di belakang seperti menjepit koin.',
    defaultRepRange: '8-10 reps',
  },
  {
    id: 'guide-tbar-row',
    name: 'Chest-Supported T-Bar Row',
    nameId: 'Mesin T-Bar Row Sandaran Dada',
    muscleCategory: 'back',
    subMuscle: 'rhomboids_traps',
    subMuscleId: 'Punggung Tengah / Ketebalan',
    equipment: 'machine',
    equipmentNameId: 'Mesin T-Bar Row Plate Loaded',
    difficulty: 'intermediate',
    equipmentLookFor: 'Mesin miring dengan bantalan dada empuk dan tuas pegangan beban piringan (*plate*).',
    setupTips: 'Tempelkan dada penuh di bantalan. Keuntungan mesin ini adalah punggung bawah aman 100% tanpa beban stres tulang belakang.',
    mindMuscleCue: 'Tarik pegangan ke arah dada atas dan rasakan kontraksi tebal di antara kedua tulang belikat.',
    defaultRepRange: '8-10 reps',
  },
  {
    id: 'guide-hyperextension',
    name: 'Back Extension (Hyperextension)',
    nameId: 'Back Extension / Kursi Romawi',
    muscleCategory: 'back',
    subMuscle: 'lower_back',
    subMuscleId: 'Pinggang Bawah',
    equipment: 'bodyweight',
    equipmentNameId: 'Bangku Roman Chair 45°',
    difficulty: 'beginner',
    equipmentLookFor: 'Bangku miring 45 derajat dengan bantalan paha atas dan penahan tumit belakang.',
    setupTips: 'Atur bantalan tepat di bawah tulang pinggul agar panggul bebas menekuk.',
    mindMuscleCue: 'Turun perlahan, lalu angkat tubuh sampai lurus sejajar kaki. Jangan melengkung berlebihan ke belakang (*overextend*).',
    defaultRepRange: '10-12 reps',
  },

  // ================= BAHU (SHOULDERS) =================
  {
    id: 'guide-seated-db-shoulder-press',
    name: 'Seated DB Shoulder Press',
    nameId: 'Shoulder Press Dumbbell Duduk',
    muscleCategory: 'shoulders',
    subMuscle: 'front_delt',
    subMuscleId: 'Bahu Depan',
    equipment: 'dumbbell',
    equipmentNameId: 'Dumbbell & Bangku Tegak 75°–85°',
    difficulty: 'intermediate',
    equipmentLookFor: 'Bangku disetel hampir tegak (beri sedikit kemiringan ~75-80° agar sendi bahu lebih natural).',
    setupTips: 'Posisikan siku sedikit mengarah ke depan (~30° di bidang scapular plane), bukan dibuka lebar 180° ke samping.',
    mindMuscleCue: 'Dorong dumbbell lurus ke atas hingga di atas kepala tanpa membenturkan kedua dumbbell.',
    defaultRepRange: '8-10 reps',
  },
  {
    id: 'guide-cable-lateral-raise',
    name: 'Cable Lateral Raise',
    nameId: 'Lateral Raise Kabel Satu Tangan',
    muscleCategory: 'shoulders',
    subMuscle: 'side_delt',
    subMuscleId: 'Bahu Samping (V-Taper)',
    equipment: 'cable',
    equipmentNameId: 'Mesin Kabel Rendah (Single Handle)',
    difficulty: 'beginner',
    equipmentLookFor: 'Katrol kabel diatur paling bawah setinggi lutut atau pergelangan kaki.',
    setupTips: 'Berdiri di samping tiang kabel, pegang handle di tangan yang jauh. Kabel memberikan ketegangan konstan (*constant tension*) dari titik terbawah.',
    mindMuscleCue: 'Pimpin gerakan dengan siku ke arah samping atas. Bayangkan mendorong dinding di samping Anda.',
    defaultRepRange: '12-15 reps',
  },
  {
    id: 'guide-machine-rear-delt-fly',
    name: 'Reverse Pec Deck (Rear Delt Fly)',
    nameId: 'Reverse Pec Deck Fly (Bahu Belakang)',
    muscleCategory: 'shoulders',
    subMuscle: 'rear_delt',
    subMuscleId: 'Bahu Belakang (3D Look)',
    equipment: 'machine',
    equipmentNameId: 'Mesin Pec Deck / Rear Delt',
    difficulty: 'beginner',
    equipmentLookFor: 'Mesin pec deck yang sama dengan fly dada, tetapi posisi duduk menghadap ke bantalan kursi.',
    setupTips: 'Duduk menghadap bantalan mesin, atur tuas ke posisi paling belakang. Pegang tuas horizontal atau netral.',
    mindMuscleCue: 'Buka lengan ke arah samping belakang dengan siku sedikit ditekuk. Fokus pada bagian belakang bahu Anda.',
    defaultRepRange: '12-15 reps',
  },

  // ================= LENGAN (ARMS) =================
  {
    id: 'guide-cable-rope-pushdown',
    name: 'Cable Rope Tricep Pushdown',
    nameId: 'Tricep Rope Pushdown Kabel',
    muscleCategory: 'arms',
    subMuscle: 'triceps',
    subMuscleId: 'Triceps',
    equipment: 'cable',
    equipmentNameId: 'Mesin Kabel Tinggi & Tali Rope',
    difficulty: 'beginner',
    equipmentLookFor: 'Katrol kabel di posisi atas dipasangi aksesori tali tambang bercabang (*rope attachment*).',
    setupTips: 'Kunci siku rapat di sisi pinggang tubuh. Siku tidak boleh maju-mundur saat bergerak.',
    mindMuscleCue: 'Dorong tali ke bawah dan buka ujung tali ke arah luar di bagian bawah untuk kontraksi puncak tricep lateral.',
    defaultRepRange: '10-12 reps',
  },
  {
    id: 'guide-incline-dumbbell-curl',
    name: 'Incline Dumbbell Bicep Curl',
    nameId: 'Incline Dumbbell Bicep Curl',
    muscleCategory: 'arms',
    subMuscle: 'biceps',
    subMuscleId: 'Biceps (Long Head Peak)',
    equipment: 'dumbbell',
    equipmentNameId: 'Dumbbell & Bangku Incline 45°–60°',
    difficulty: 'intermediate',
    equipmentLookFor: 'Bangku disetel miring 45-60 derajat ke belakang.',
    setupTips: 'Duduk bersandar penuh. Biarkan kedua lengan menggantung lurus ke bawah di belakang badan untuk peregangan bicep maksimal.',
    mindMuscleCue: 'Tekuk siku memutar telapak tangan menghadap ke atas (*supinasi*). Peregangan posisi ini sangat kuat menstimulasi *bicep peak*.',
    defaultRepRange: '8-10 reps',
  },
  {
    id: 'guide-hammer-curl',
    name: 'Dumbbell Hammer Curl',
    nameId: 'Hammer Curl Dumbbell (Posisi Martil)',
    muscleCategory: 'arms',
    subMuscle: 'brachialis',
    subMuscleId: 'Brachialis & Ketebalan Lengan',
    equipment: 'dumbbell',
    equipmentNameId: 'Sepasang Dumbbell',
    difficulty: 'beginner',
    equipmentLookFor: 'Dumbbell dengan berat sedang di rak free weights.',
    setupTips: 'Berdiri tegap, telapak tangan saling berhadapan (*neutral grip*) seperti memegang palu/martil.',
    mindMuscleCue: 'Angkat dumbbell tanpa memutar pergelangan tangan. Ini melatih otot Brachialis di bawah bicep yang mendorong lingkar lengan lebih tebal.',
    defaultRepRange: '10-12 reps',
  },

  // ================= KAKI (LEGS) =================
  {
    id: 'guide-leg-press-45',
    name: '45° Incline Leg Press',
    nameId: 'Mesin Leg Press 45 Derajat',
    muscleCategory: 'legs',
    subMuscle: 'quads',
    subMuscleId: 'Paha Depan & Bokong',
    equipment: 'machine',
    equipmentNameId: 'Mesin Leg Press Plat 45°',
    difficulty: 'intermediate',
    equipmentLookFor: 'Sled pelat beban besar dengan platform pijakan kaki lebar dan tuas pengaman samping.',
    setupTips: 'Bantalan punggung menempel rapat. Letakkan kaki selebar bahu di tengah platform. Buka tuas pengaman sebelum menurunkan beban.',
    mindMuscleCue: 'Turunkan beban sampai lutut membentuk 90°, jangan sampai bokong terangkat dari kursi (*butt wink*). Dorong dengan seluruh telapak kaki tanpa mengunci mati lutut di atas.',
    defaultRepRange: '8-10 reps',
  },
  {
    id: 'guide-leg-extension',
    name: 'Seated Leg Extension Machine',
    nameId: 'Mesin Leg Extension (Paha Depan Isolasi)',
    muscleCategory: 'legs',
    subMuscle: 'quads',
    subMuscleId: 'Paha Depan (Isolasi)',
    equipment: 'machine',
    equipmentNameId: 'Mesin Leg Extension Duduk',
    difficulty: 'beginner',
    equipmentLookFor: 'Mesin duduk dengan bantalan busa silinder di atas pergelangan kaki depan.',
    setupTips: 'Atur sandaran agar poros putaran mesin sejajar dengan sendi lutut Anda.',
    mindMuscleCue: 'Tendang lurus ke atas dan tahan 1 detik di puncak kontraksi untuk isolasi serat paha depan.',
    defaultRepRange: '10-12 reps',
  },
  {
    id: 'guide-lying-leg-curl',
    name: 'Lying Leg Curl Machine',
    nameId: 'Mesin Leg Curl Rebahan (Paha Belakang)',
    muscleCategory: 'legs',
    subMuscle: 'hamstrings',
    subMuscleId: 'Paha Belakang (Hamstrings)',
    equipment: 'machine',
    equipmentNameId: 'Mesin Lying Leg Curl',
    difficulty: 'beginner',
    equipmentLookFor: 'Bantalan panjang untuk tengkurap dengan roll busa penahan di atas tumit belakang.',
    setupTips: 'Tengkurap rapat, posisikan bantalan busa tepat di bawah betis/di atas tumit belakang Achilles.',
    mindMuscleCue: 'Tarik tumit mendekati bokong, tahan kontraksi 1 detik, lalu turunkan terkontrol 3 detik.',
    defaultRepRange: '10-12 reps',
  },
  {
    id: 'guide-standing-calf-raise',
    name: 'Standing Calf Raise Machine',
    nameId: 'Mesin Calf Raise Berdiri (Betis)',
    muscleCategory: 'legs',
    subMuscle: 'calves',
    subMuscleId: 'Betis',
    equipment: 'machine',
    equipmentNameId: 'Mesin Calf Raise Berdiri / Smith Machine',
    difficulty: 'beginner',
    equipmentLookFor: 'Mesin berdiri dengan bantalan bahu dan balok pijakan kaki.',
    setupTips: 'Pijakkan bagian depan telapak kaki di pinggir balok, biarkan tumit menggantung bebas ke bawah.',
    mindMuscleCue: 'Turunkan tumit sedalam mungkin untuk peregangan betis penuh, lalu jinjit setinggi-tingginya dan tahan 1 detik.',
    defaultRepRange: '12-15 reps',
  },

  // ================= PERUT & CORE =================
  {
    id: 'guide-cable-kneeling-crunch',
    name: 'Kneeling Cable Crunch',
    nameId: 'Cable Crunch Berlutut (Perut Atas & Tengah)',
    muscleCategory: 'core',
    subMuscle: 'abs',
    subMuscleId: 'Six-Pack / Perut',
    equipment: 'cable',
    equipmentNameId: 'Mesin Kabel Tinggi & Tali Rope',
    difficulty: 'intermediate',
    equipmentLookFor: 'Katrol kabel di posisi atas dengan tali tambang rope attachment.',
    setupTips: 'Berlutut di depan mesin kabel, tahan tali di samping telinga atau dahi kepala.',
    mindMuscleCue: 'Tekuk tulang belakang Anda mendekatkan tulang rusuk ke arah panggul. Jangan gunakan pinggul untuk mengayun.',
    defaultRepRange: '12-15 reps',
  },
  {
    id: 'guide-hanging-knee-raise',
    name: 'Hanging Knee Raise',
    nameId: 'Hanging Knee Raise (Perut Bawah)',
    muscleCategory: 'core',
    subMuscle: 'abs',
    subMuscleId: 'Perut Bawah',
    equipment: 'bodyweight',
    equipmentNameId: 'Palang Pull-up / Kursi Captains Chair',
    difficulty: 'intermediate',
    equipmentLookFor: 'Palang gantung atau bangku penyangga siku *Captain’s Chair*.',
    setupTips: 'Gantung tubuh dengan stabil tanpa mengayun tubuh (*swinging*).',
    mindMuscleCue: 'Tarik lutut ke arah dada sambil memutar panggul ke atas (*posterior pelvic tilt*) agar otot perut bawah benar-benar berkontraksi.',
    defaultRepRange: '10-15 reps',
  },
];
